# Is performed before the scripts in the stages step
before_script:  
  - source /etc/profile

# Defines stages which are to be executed
stages:  
  - build

# Stage "ubuntu"
build-ubuntu-1804-64:  
  stage: build
  script:
    - cd openfortigui
    - git submodule init && git submodule update
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ../krunner_openfortigui
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd .. && mkdir build
    - mv openforti*.deb build/
    - upload_build build/openforti*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-1804-64

# Stage "ubuntu"
build-ubuntu-1604-64:  
  stage: build
  script:
    - cd openfortigui
    - git submodule init && git submodule update
    - debuild clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ../krunner_openfortigui
    - debuild clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd .. && mkdir build
    - mv openforti*.deb build/
    - upload_build build/openforti*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-1604-64
    
# Stage "ubuntu"
build-ubuntu-1604-32:  
  stage: build
  script:
    - cd openfortigui
    - git submodule init && git submodule update
    - debuild clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ../krunner_openfortigui
    - debuild clean
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd .. && mkdir build
    - mv openforti*.deb build/
    - upload_build build/openforti*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-ubuntu-1604-32

# Stage "debian"
build-debian-9-64:  
  stage: build
  script:
    - cd openfortigui
    - git submodule init && git submodule update
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ../krunner_openfortigui
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd .. && mkdir build
    - mv openfortigui_*.deb build/
    - mv openfortigui-runner_*.deb build/
    - upload_build build/openforti*.deb || true
    
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-9-64

# Stage "debian"
build-debian-10-64:  
  stage: build
  script:
    - cd openfortigui
    - git submodule init && git submodule update
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd ../krunner_openfortigui
    - echo "y" | debuild -eDEB_BUILD_OPTIONS="parallel=4" -us -uc
    - cd .. && mkdir build
    - mv openfortigui_*.deb build/
    - mv openfortigui-runner_*.deb build/
    - upload_build build/openforti*.deb || true

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

  tags:
    - build-debian-10-64
